# 01-PyTorch Basics

In [ ]:
import torch

## Tensors

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.dtype

torch.float32

In [8]:
t3 = torch.tensor([
    [5.,6.],
    [7,8],
    [9,10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
t3.shape

torch.Size([3, 2])

In [10]:
# 3d tensor
t4 = torch.tensor([
    [
        [11.,12,13],
        [24,25,26]
    ],
    [
        [1.,2,3],
        [4,5,6]
    ]
])
t4

tensor([[[11., 12., 13.],
         [24., 25., 26.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [12]:
t5 = torch.tensor([
    [1.,2,3,6],
    [4,5]
])
t5.shape

ValueError: expected sequence of length 4 at dim 1 (got 2)

## Tensor Operations and Gradients

In [13]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [14]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
# compute derivatives
y.backward()

# display gradients
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


## Tensor Functions

In [16]:
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [17]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [18]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [19]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [20]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Numpy Interoperatibility

In [21]:
import numpy as np

In [22]:
x = np.array([
    [1,2],
    [3,4]
])

x

array([[1, 2],
       [3, 4]])

In [23]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [24]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [25]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

# 02-Linear Regression

In [26]:
import numpy as np
import torch

In [27]:
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
], dtype='float32')

In [28]:
targets = np.array([
    [56,70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
], dtype='float32')

In [29]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [30]:
# weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
w,b

(tensor([[ 2.1631, -0.5117, -1.2191],
         [-0.7589,  0.2787,  1.3698]], requires_grad=True),
 tensor([-0.3020, -2.3193], requires_grad=True))

In [31]:
def model(x):
    return x @ w.t() + b

In [33]:
inputs @ w.t() + b

tensor([[ 70.8965,  19.8524],
        [ 73.4845,  40.8098],
        [ 48.6097,  48.4464],
        [153.2206, -17.0637],
        [ 14.4887,  67.9544]], grad_fn=<AddBackward0>)

In [34]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 70.8965,  19.8524],
        [ 73.4845,  40.8098],
        [ 48.6097,  48.4464],
        [153.2206, -17.0637],
        [ 14.4887,  67.9544]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Loss Function

In [ ]:
# mean squared error
diff = preds - targets
torch.sum(diff * diff) / diff.numel()

tensor(4910.1763, grad_fn=<DivBackward0>)

In [37]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff * diff) / diff.numel()

In [38]:
loss = mse(preds, targets)
loss

tensor(4910.1763, grad_fn=<DivBackward0>)

### Gradient Computation

In [ ]:
# compute gradients
loss.backward()

In [42]:
print(w)
print(w.grad)

tensor([[ 2.1631, -0.5117, -1.2191],
        [-0.7589,  0.2787,  1.3698]], requires_grad=True)
tensor([[  311.3613, -2390.0381, -1052.7407],
        [-5106.1777, -5442.3853, -3297.2354]])


In [44]:
print(b, b.grad, sep="\n")

tensor([-0.3020, -2.3193], requires_grad=True)
tensor([ -4.0600, -60.0001])


In [45]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [46]:
w,b

(tensor([[ 2.1600, -0.4878, -1.2086],
         [-0.7079,  0.3331,  1.4028]], requires_grad=True),
 tensor([-0.3020, -2.3187], requires_grad=True))

In [47]:
preds = model(inputs)
loss = mse(preds, targets)
loss


tensor(4238.0513, grad_fn=<DivBackward0>)

In [48]:
# reset gradients to zero 
w.grad.zero_()
b.grad.zero_()
w.grad, b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

In [49]:
# Training for mutiple epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()

    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [50]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(915.8505, grad_fn=<DivBackward0>)

In [51]:
preds

tensor([[ 70.7380,  69.1826],
        [ 80.5403, 105.0293],
        [100.6622, 124.8483],
        [ 99.1762,  33.2359],
        [ 53.3872, 128.4700]], grad_fn=<AddBackward0>)

In [54]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## Using PyTorch

In [55]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

In [56]:
from torch.utils.data import TensorDataset

In [57]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [58]:
from torch.utils.data import DataLoader

In [59]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [60]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [103.,  43.,  36.]])
tensor([[ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [ 20.,  38.]])


In [64]:
# defining model
model = torch.nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3555, -0.0212, -0.0714],
        [-0.0643, -0.1009,  0.3371]], requires_grad=True)
Parameter containing:
tensor([ 0.0622, -0.4012], requires_grad=True)


In [65]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3555, -0.0212, -0.0714],
         [-0.0643, -0.1009,  0.3371]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0622, -0.4012], requires_grad=True)]

In [66]:
# predictions
preds = model(inputs)
preds

tensor([[-3.0383e+01,  2.6399e+00],
        [-3.8727e+01,  6.4431e+00],
        [-3.7853e+01,  3.4102e-02],
        [-3.9754e+01,  1.1752e+00],
        [-3.1504e+01,  9.0728e+00],
        [-3.0717e+01,  2.6766e+00],
        [-3.8777e+01,  6.8811e+00],
        [-3.8280e+01,  3.0696e-01],
        [-3.9420e+01,  1.1385e+00],
        [-3.1220e+01,  9.4743e+00],
        [-3.0433e+01,  3.0780e+00],
        [-3.9061e+01,  6.4797e+00],
        [-3.7803e+01, -4.0399e-01],
        [-4.0038e+01,  7.7374e-01],
        [-3.1170e+01,  9.0362e+00]], grad_fn=<AddmmBackward0>)

### Loss Function

In [67]:
# Loss function
import torch.nn.functional as F

In [69]:
loss_fn = F.mse_loss

In [70]:
loss = loss_fn(model(inputs), targets)
loss

tensor(11256.1768, grad_fn=<MseLossBackward0>)

### Optimizers

In [72]:
# Optimizers
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Model Training

In [75]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epochs in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        
        if (epochs+1) % 10 == 0:
            print("Epoch [{}/{}], Loss: {:.4f}".format(epochs+1, num_epochs, loss.item()))


In [76]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 98.2636
Epoch [20/100], Loss: 146.2914
Epoch [30/100], Loss: 138.7637
Epoch [40/100], Loss: 40.6946
Epoch [50/100], Loss: 62.5286
Epoch [60/100], Loss: 33.5145
Epoch [70/100], Loss: 24.6818
Epoch [80/100], Loss: 16.7038
Epoch [90/100], Loss: 23.3592
Epoch [100/100], Loss: 12.5872


In [77]:
preds = model(inputs)
preds

tensor([[ 57.8202,  71.1819],
        [ 80.5741, 100.0213],
        [120.2630, 132.6655],
        [ 25.4818,  42.6414],
        [ 96.6038, 114.6732],
        [ 56.6405,  70.2137],
        [ 80.1129,  99.9669],
        [120.4113, 133.2232],
        [ 26.6615,  43.6096],
        [ 97.3224, 115.5870],
        [ 57.3590,  71.1275],
        [ 79.3944,  99.0531],
        [120.7242, 132.7199],
        [ 24.7633,  41.7277],
        [ 97.7835, 115.6414]], grad_fn=<AddmmBackward0>)

In [79]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [80]:
model(torch.tensor([[75., 63, 44]]))

tensor([[54.1051, 68.4010]], grad_fn=<AddmmBackward0>)