# 01-PyTorch Basics

In [1]:
import torch

## Tensors

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t2.dtype

torch.float32

In [6]:
t3 = torch.tensor([
    [5.,6.],
    [7,8],
    [9,10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
t3.shape

torch.Size([3, 2])

In [8]:
# 3d tensor
t4 = torch.tensor([
    [
        [11.,12,13],
        [24,25,26]
    ],
    [
        [1.,2,3],
        [4,5,6]
    ]
])
t4

tensor([[[11., 12., 13.],
         [24., 25., 26.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]]])

In [9]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
t5 = torch.tensor([
    [1.,2,3,6],
    [4,5]
])
t5.shape  # error 

ValueError: expected sequence of length 4 at dim 1 (got 2)

## Tensor Operations and Gradients

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# compute derivatives
y.backward()

# display gradients
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


## Tensor Functions

In [14]:
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [15]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [16]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [17]:
t7.shape

torch.Size([6, 2])

In [18]:
t7_5 = torch.cat([t3, t6], dim=1)
t7_5

tensor([[ 5.,  6., 42., 42.],
        [ 7.,  8., 42., 42.],
        [ 9., 10., 42., 42.]])

In [19]:
t7_5.shape

torch.Size([3, 4])

In [20]:
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [21]:
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Numpy Interoperatibility

In [22]:
import numpy as np

In [23]:
x = np.array([
    [1,2],
    [3,4]
])

x

array([[1, 2],
       [3, 4]])

In [24]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [25]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [26]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [27]:
z.dtype

dtype('int64')

# 02-Linear Regression

In [28]:
import numpy as np
import torch

In [29]:
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
], dtype='float32')

In [30]:
targets = np.array([
    [56,70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
], dtype='float32')

In [31]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [32]:
# weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
w,b

(tensor([[ 0.9039, -0.9580, -0.9521],
         [-0.7145,  1.1121,  1.9110]], requires_grad=True),
 tensor([-0.3088,  0.1243], requires_grad=True))

In [33]:
def model(x):
    return x @ w.t() + b

In [34]:
inputs @ w.t() + b

tensor([[ -39.4537,  104.6473],
        [ -63.2961,  155.2712],
        [-105.2693,  197.8199],
        [  15.4640,   45.7689],
        [ -96.5580,  191.3542]], grad_fn=<AddBackward0>)

In [35]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ -39.4537,  104.6473],
        [ -63.2961,  155.2712],
        [-105.2693,  197.8199],
        [  15.4640,   45.7689],
        [ -96.5580,  191.3542]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Loss Function

In [36]:
# mean squared error
diff = preds - targets
torch.sum(diff * diff) / diff.numel()

tensor(13375.5029, grad_fn=<DivBackward0>)

In [38]:
diff

tensor([[ -95.4537,   34.6473],
        [-144.2961,   54.2712],
        [-224.2693,   64.8199],
        [  -6.5360,    8.7689],
        [-199.5580,   72.3542]], grad_fn=<SubBackward0>)

In [ ]:
diff.numel() # len

10

In [39]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff * diff) / diff.numel()

In [40]:
loss = mse(preds, targets)
loss

tensor(13375.5029, grad_fn=<DivBackward0>)

### Gradient Computation

In [41]:
# compute gradients
loss.backward()

In [42]:
print(w)
print(w.grad)

tensor([[ 0.9039, -0.9580, -0.9521],
        [-0.7145,  1.1121,  1.9110]], requires_grad=True)
tensor([[-10809.3330, -13716.8301,  -8111.5938],
        [  3798.8262,   4621.2339,   2822.3977]])


In [43]:
print(b, b.grad, sep="\n")

tensor([-0.3088,  0.1243], requires_grad=True)
tensor([-134.0226,   46.9723])


In [44]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [45]:
w,b

(tensor([[ 1.0120, -0.8209, -0.8709],
         [-0.7525,  1.0659,  1.8828]], requires_grad=True),
 tensor([-0.3074,  0.1239], requires_grad=True))

In [46]:
preds = model(inputs)
loss = mse(preds, targets)
loss


tensor(9599.1426, grad_fn=<DivBackward0>)

In [47]:
# reset gradients to zero 
w.grad.zero_()
b.grad.zero_()
w.grad, b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

In [48]:
# Training for mutiple epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()

    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [49]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(569.8442, grad_fn=<DivBackward0>)

In [50]:
preds

tensor([[ 67.4303,  67.2096],
        [ 82.5689, 104.2483],
        [101.3659, 129.8040],
        [ 80.3796,  19.4532],
        [ 67.8857, 135.6353]], grad_fn=<AddBackward0>)

In [51]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## Using PyTorch

In [52]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

In [53]:
from torch.utils.data import TensorDataset

In [54]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [55]:
from torch.utils.data import DataLoader

In [57]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [58]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [103.,  43.,  36.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [ 20.,  38.],
        [ 56.,  70.],
        [118., 134.]])


In [59]:
# defining model
model = torch.nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2757,  0.1019, -0.2696],
        [-0.5658,  0.5508, -0.0609]], requires_grad=True)
Parameter containing:
tensor([-0.5566, -0.0421], requires_grad=True)


In [60]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2757,  0.1019, -0.2696],
         [-0.5658,  0.5508, -0.0609]], requires_grad=True),
 Parameter containing:
 tensor([-0.5566, -0.0421], requires_grad=True)]

In [61]:
# predictions
preds = model(inputs)
preds

tensor([[ 14.8064,  -7.0590],
        [ 16.2485,  -6.9555],
        [ 21.4508,  21.0104],
        [ 21.9731, -36.3197],
        [  9.3811,   9.5321],
        [ 14.9802,  -8.1755],
        [ 15.8770,  -7.5672],
        [ 21.4569,  20.3837],
        [ 21.7993, -35.2031],
        [  8.8359,  10.0369],
        [ 14.4350,  -7.6707],
        [ 16.4222,  -8.0720],
        [ 21.8223,  21.6221],
        [ 22.5184, -36.8245],
        [  9.2073,  10.6486]], grad_fn=<AddmmBackward0>)

### Loss Function

In [62]:
# Loss function
import torch.nn.functional as F

In [63]:
loss_fn = F.mse_loss

In [64]:
loss = loss_fn(model(inputs), targets)
loss

tensor(7169.1455, grad_fn=<MseLossBackward0>)

### Optimizers

In [65]:
# Optimizers
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Model Training

In [66]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epochs in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        
        if (epochs+1) % 10 == 0:
            print("Epoch [{}/{}], Loss: {:.4f}".format(epochs+1, num_epochs, loss.item()))


In [67]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 327.2477
Epoch [20/100], Loss: 406.5924
Epoch [30/100], Loss: 217.5829
Epoch [40/100], Loss: 100.4476
Epoch [50/100], Loss: 100.0204
Epoch [60/100], Loss: 90.2887
Epoch [70/100], Loss: 32.3053
Epoch [80/100], Loss: 57.3630
Epoch [90/100], Loss: 48.2487
Epoch [100/100], Loss: 27.4144


In [68]:
preds = model(inputs)
preds

tensor([[ 58.6074,  70.8146],
        [ 79.3187,  96.9297],
        [122.3681, 140.2661],
        [ 30.0718,  39.8845],
        [ 91.5811, 110.9771],
        [ 57.4980,  69.6636],
        [ 78.5551,  96.3581],
        [122.3856, 140.5047],
        [ 31.1812,  41.0355],
        [ 91.9268, 111.5565],
        [ 57.8437,  70.2430],
        [ 78.2094,  95.7787],
        [123.1317, 140.8377],
        [ 29.7261,  39.3051],
        [ 92.6905, 112.1281]], grad_fn=<AddmmBackward0>)

In [69]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])