# 02-Linear Regression

In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
], dtype='float32')

In [ ]:
targets = np.array([
    [56,70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [ ]:
# weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
w,b

(tensor([[ 2.1631, -0.5117, -1.2191],
         [-0.7589,  0.2787,  1.3698]], requires_grad=True),
 tensor([-0.3020, -2.3193], requires_grad=True))

In [ ]:
def model(x):
    return x @ w.t() + b

In [ ]:
inputs @ w.t() + b

tensor([[ 70.8965,  19.8524],
        [ 73.4845,  40.8098],
        [ 48.6097,  48.4464],
        [153.2206, -17.0637],
        [ 14.4887,  67.9544]], grad_fn=<AddBackward0>)

In [ ]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 70.8965,  19.8524],
        [ 73.4845,  40.8098],
        [ 48.6097,  48.4464],
        [153.2206, -17.0637],
        [ 14.4887,  67.9544]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Loss Function

In [ ]:
# mean squared error
diff = preds - targets
torch.sum(diff * diff) / diff.numel()

tensor(4910.1763, grad_fn=<DivBackward0>)

In [ ]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
loss = mse(preds, targets)
loss

tensor(4910.1763, grad_fn=<DivBackward0>)

### Gradient Computation

In [ ]:
# compute gradients
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 2.1631, -0.5117, -1.2191],
        [-0.7589,  0.2787,  1.3698]], requires_grad=True)
tensor([[  311.3613, -2390.0381, -1052.7407],
        [-5106.1777, -5442.3853, -3297.2354]])


In [ ]:
print(b, b.grad, sep="\n")

tensor([-0.3020, -2.3193], requires_grad=True)
tensor([ -4.0600, -60.0001])


In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [ ]:
w,b

(tensor([[ 2.1600, -0.4878, -1.2086],
         [-0.7079,  0.3331,  1.4028]], requires_grad=True),
 tensor([-0.3020, -2.3187], requires_grad=True))

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
loss


tensor(4238.0513, grad_fn=<DivBackward0>)

In [ ]:
# reset gradients to zero 
w.grad.zero_()
b.grad.zero_()
w.grad, b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

In [ ]:
# Training for mutiple epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()

    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(915.8505, grad_fn=<DivBackward0>)

In [ ]:
preds

tensor([[ 70.7380,  69.1826],
        [ 80.5403, 105.0293],
        [100.6622, 124.8483],
        [ 99.1762,  33.2359],
        [ 53.3872, 128.4700]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

## Using PyTorch

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [103.,  43.,  36.]])
tensor([[ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [ 20.,  38.]])


In [ ]:
# defining model
model = torch.nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3555, -0.0212, -0.0714],
        [-0.0643, -0.1009,  0.3371]], requires_grad=True)
Parameter containing:
tensor([ 0.0622, -0.4012], requires_grad=True)


In [ ]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3555, -0.0212, -0.0714],
         [-0.0643, -0.1009,  0.3371]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0622, -0.4012], requires_grad=True)]

In [ ]:
# predictions
preds = model(inputs)
preds

tensor([[-3.0383e+01,  2.6399e+00],
        [-3.8727e+01,  6.4431e+00],
        [-3.7853e+01,  3.4102e-02],
        [-3.9754e+01,  1.1752e+00],
        [-3.1504e+01,  9.0728e+00],
        [-3.0717e+01,  2.6766e+00],
        [-3.8777e+01,  6.8811e+00],
        [-3.8280e+01,  3.0696e-01],
        [-3.9420e+01,  1.1385e+00],
        [-3.1220e+01,  9.4743e+00],
        [-3.0433e+01,  3.0780e+00],
        [-3.9061e+01,  6.4797e+00],
        [-3.7803e+01, -4.0399e-01],
        [-4.0038e+01,  7.7374e-01],
        [-3.1170e+01,  9.0362e+00]], grad_fn=<AddmmBackward0>)

### Loss Function

In [ ]:
# Loss function
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
loss

tensor(11256.1768, grad_fn=<MseLossBackward0>)

### Optimizers

In [ ]:
# Optimizers
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Model Training

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epochs in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        
        if (epochs+1) % 10 == 0:
            print("Epoch [{}/{}], Loss: {:.4f}".format(epochs+1, num_epochs, loss.item()))


In [ ]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 98.2636
Epoch [20/100], Loss: 146.2914
Epoch [30/100], Loss: 138.7637
Epoch [40/100], Loss: 40.6946
Epoch [50/100], Loss: 62.5286
Epoch [60/100], Loss: 33.5145
Epoch [70/100], Loss: 24.6818
Epoch [80/100], Loss: 16.7038
Epoch [90/100], Loss: 23.3592
Epoch [100/100], Loss: 12.5872


In [ ]:
preds = model(inputs)
preds

tensor([[ 57.8202,  71.1819],
        [ 80.5741, 100.0213],
        [120.2630, 132.6655],
        [ 25.4818,  42.6414],
        [ 96.6038, 114.6732],
        [ 56.6405,  70.2137],
        [ 80.1129,  99.9669],
        [120.4113, 133.2232],
        [ 26.6615,  43.6096],
        [ 97.3224, 115.5870],
        [ 57.3590,  71.1275],
        [ 79.3944,  99.0531],
        [120.7242, 132.7199],
        [ 24.7633,  41.7277],
        [ 97.7835, 115.6414]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75., 63, 44]]))

tensor([[54.1051, 68.4010]], grad_fn=<AddmmBackward0>)